name: tjepa
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scikit-learn
  - pip
  - pip:
      - torch>=2.4
      - einops
      - rich
      - typer
      - ruff
      - pytest
      - pytest-cov
